section .data

EFFECT_TABLE_WIDTH equ 24 * 8

EFFECT_TABLE:
; 0  R | 0  R                   1  Y                   2  S                   3  C                   4  c                   5  Q                   6  Z                   7  z                   8  W                   9  X                   10 x                   11 I                   12 N                   13 F                   14 f                   15 <                   16 =                   17 >                   18 &                   19 |                   20 !                   21 i                   22 0                   23 1                  
dq       00                   , push_symbol          , push_string          , push_char            , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , push_collect_ident   , push_collect_int     , err_invalid_effect   , err_invalid_effect   , push_symbol          , push_symbol          , push_symbol          , push_symbol          , push_symbol          , push_symbol          , err_invalid_effect   , err_invalid_char     , err_invalid_effect   
; 1  Y
dq       push_symbol          , 00                   , push_string          , push_char            , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , push_collect_ident   , push_collect_int     , err_invalid_effect   , err_invalid_effect   , push_symbol          , push_symbol          , push_symbol          , push_symbol          , push_symbol          , push_symbol          , err_invalid_effect   , err_invalid_char     , err_invalid_effect   
; 2  S
dq       push_buffer          , err_invalid_effect   , collect              , err_invalid_effect   , err_invalid_effect   , 0                    , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_expected_str_term, err_invalid_effect   
; 3  C
dq       err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , collect              , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , 00                   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_null_chr , err_expected_chr_term
; 4  c
dq       push_buffer          , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_expected_chr_term, err_invalid_effect   
; 5  Q
dq       err_invalid_effect   , err_invalid_effect   , collect_dqoute       , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , 00                   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_str_esc  , err_invalid_effect   
; 6  Z
dq       err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , collect_upper_hex    , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_hex_esc  , err_invalid_effect   
; 7  z
dq       err_invalid_effect   , err_invalid_effect   , collect_lower_hex    , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_hex_esc  , err_invalid_effect   
; 8  W
dq       err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , collect_sqoute       , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , 00                   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_chr_esc  , err_invalid_effect   
; 9  X
dq       err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , collect_upper_hex    , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_hex_esc  , err_invalid_effect   
; 10 x
dq       err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , collect_lower_hex    , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_hex_esc  , err_invalid_effect   
; 11 I
dq       push_buffer          , push_symbol          , push_string          , push_char            , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , collect              , collect              , err_invalid_effect   , err_invalid_effect   , push_symbol          , push_symbol          , push_symbol          , push_symbol          , push_symbol          , push_symbol          , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   
; 12 N
dq       push_buffer          , push_symbol          , push_string          , push_char            , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , collect              , collect              , into_float_collect   , err_invalid_effect   , push_symbol          , push_symbol          , push_symbol          , push_symbol          , push_symbol          , push_symbol          , err_invalid_effect   , err_invalid_char     , err_invalid_number   
; 13 F
dq       err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , collect              , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_float    , err_invalid_effect   
; 14 f
dq       push_buffer          , push_symbol          , push_string          , push_char            , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , push_collect_ident   , err_invalid_effect   , err_invalid_effect   , collect              , push_symbol          , push_symbol          , push_symbol          , push_symbol          , push_symbol          , push_symbol          , err_invalid_effect   , err_invalid_char     , err_invalid_float    
; 15 <
dq       push_symbol          , into_lesseq          , push_string          , push_char            , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , push_collect_ident   , push_collect_int     , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , 00                   , err_invalid_char     , err_invalid_effect   
; 16 =
dq       push_symbol          , into_dequal          , push_string          , push_char            , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , push_collect_ident   , push_collect_int     , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , 00                   , err_invalid_char     , err_invalid_effect   
; 17 >
dq       push_symbol          , into_greateq         , push_string          , push_char            , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , push_collect_ident   , push_collect_int     , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , 00                   , err_invalid_char     , err_invalid_effect   
; 18 &
dq       push_symbol          , into_damp            , push_string          , push_char            , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , push_collect_ident   , push_collect_int     , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , 00                   , err_invalid_char     , err_invalid_effect   
; 19 |
dq       push_symbol          , into_dvbar           , push_string          , push_char            , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , push_collect_ident   , push_collect_int     , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , 00                   , err_invalid_char     , err_invalid_effect   
; 20 !
dq       push_symbol          , into_nequal          , push_string          , push_char            , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , push_collect_ident   , push_collect_int     , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , 00                   , err_invalid_char     , err_invalid_effect   
; 21 i
dq       00                   , push_symbol          , push_string          , push_char            , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , push_collect_ident   , push_collect_int     , err_invalid_effect   , err_invalid_effect   , push_symbol          , push_symbol          , push_symbol          , push_symbol          , push_symbol          , push_symbol          , err_invalid_effect   , err_invalid_char     , err_invalid_effect   
; 22 0
dq       err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   
; 23 1
dq       err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   , err_invalid_effect   
